# Solutions to mongodb practice questions 

#### helper function

In [1]:
import pprint
from datetime import datetime
import re

In [43]:
def Output_head(result, docs_count = 2):
    count = 1
    for doc in result:
        pprint.pprint(doc)
        print("-" * 60)
        print()
        if count >= docs_count:
            break
        count += 1

## 1. Establishing connection 

In [3]:
import pymongo

In [4]:
myclient = pymongo.MongoClient("mongodb://localhost:27017/")

In [5]:
myDb = myclient["MongoDb_Practice"]

In [6]:
myCollection = myDb["Practice_Collection"]

--------

## 2. Validating connection

In [7]:
result = myCollection.find_one()

In [8]:
result

{'_id': ObjectId('56d61033a378eccde8a83554'),
 'id': '10172-2015-CMPL',
 'certificate_number': 9304489,
 'business_name': 'UNNAMED HOT DOG VENDOR LICENSE NUMBER TA01158',
 'date': datetime.datetime(2015, 8, 21, 0, 0),
 'result': 'No Violation Issued',
 'sector': 'Mobile Food Vendor - 881',
 'address': {'city': '', 'zip': '', 'street': '', 'number': ''}}

------

## 3. Questions

### 3.1 Easy Questions

Q1. Retrieve all documents in the collection.

In [30]:
result1 = myCollection.find()

----------

Q2. Retrieve the `business_name` of all businesses.

In [60]:
query2 = {}

In [61]:
projection2 = {"business_name": 1,
              "_id": 0}

In [62]:
result2 = myCollection.find(query2, projection2)

In [64]:
Output_head(result2, 5)

{'business_name': 'NEW FINEST BUILDERS INC'}
{'business_name': 'WILFREDO DELIVERY SERVICE INC'}
{'business_name': 'AZMY KIROLES'}
{'business_name': 'LISANDRO CABRERA'}
{'business_name': 'BUILDING TO SERVE INC.'}


-----

Q3. Retrieve the `business_name` and `certificate_number` of all businesses.

In [65]:
query3 = {}

In [67]:
projection3 = {"business_name": 1,
             "certificate_number": 1,
             "_id": 0}

In [68]:
result3 = myCollection.find(query3, projection3)

In [69]:
Output_head(result3, 5)

{'certificate_number': 9304489, 'business_name': 'UNNAMED HOT DOG VENDOR LICENSE NUMBER TA01158'}
{'certificate_number': 9304816, 'business_name': 'UNNAMED HOT DOG VENDOR NO LICENSE NUMBER PROVIDED'}
{'certificate_number': 9287092, 'business_name': 'BISHWANATH BISWAS'}
{'certificate_number': 9287090, 'business_name': 'GRICEYDA M VILLAR'}
{'certificate_number': 5381180, 'business_name': 'ERIC CONSTRUCTION AND DECORATING INC.'}


---------

Q4. Find all businesses where the `result` is "Violation Issued".

In [70]:
query4 = {"result": "Violation Issued"}

In [71]:
projection4 = {}

In [72]:
result4 = myCollection.find(query4, projection4)

In [85]:
Output_head(result4, 2)

{'_id': ObjectId('56d61033a378eccde8a83593'),
 'address': {'city': 'SOUTH RICHMOND HILL',
             'number': 10718,
             'street': '123RD ST',
             'zip': 11419},
 'business_name': 'REMARK HOME IMPROVEMENT',
 'certificate_number': 5381174,
 'date': 'Sep  1 2015',
 'id': '11666-2015-CMPL',
 'result': 'Violation Issued',
 'sector': 'Home Improvement Contractor - 100'}
------------------------------------------------------------

{'_id': ObjectId('56d61033a378eccde8a83594'),
 'address': {'city': 'ASTORIA',
             'number': 3520,
             'street': '35TH ST',
             'zip': 11106},
 'business_name': 'ELSAMANODY TAMER',
 'certificate_number': 5381876,
 'date': 'Aug 27 2015',
 'id': '12003-2015-CMPL',
 'result': 'Violation Issued',
 'sector': 'Mobile Food Vendor - 881'}
------------------------------------------------------------



--------

**Q5. Find all businesses where the `result` is "No Violation Issued".**

In [86]:
query5 = {"result": "No Violation Issued"}

In [87]:
projection5 = {}

In [88]:
result5 = myCollection.find(query5, projection5)

In [90]:
Output_head(result5, 2)

{'_id': ObjectId('56d61033a378eccde8a83560'),
 'address': {'city': 'JERSEY CITY',
             'number': 160,
             'street': 'VROOM ST',
             'zip': 7306},
 'business_name': 'AZMY KIROLES',
 'certificate_number': 9318079,
 'date': 'Dec 23 2015',
 'id': '1044-2016-ENFO',
 'result': 'No Violation Issued',
 'sector': 'Mobile Food Vendor - 881'}
------------------------------------------------------------

{'_id': ObjectId('56d61033a378eccde8a8355f'),
 'address': {'city': 'BRONX',
             'number': 2234,
             'street': 'PALMER AVE',
             'zip': 10475},
 'business_name': 'LISANDRO CABRERA',
 'certificate_number': 9304139,
 'date': 'Jul 17 2015',
 'id': '10423-2015-CMPL',
 'result': 'No Violation Issued',
 'sector': 'Mobile Food Vendor - 881'}
------------------------------------------------------------



-----------

**Q6. List all unique values in the `sector` field.**

In [91]:
result6 = myCollection.distinct("sector")

In [97]:
Output_head(result6, 3)

''
------------------------------------------------------------

'Air Condtioning Law - 899'
------------------------------------------------------------

'Amusement Arcade - 014'
------------------------------------------------------------



--------

**Q7. Retrieve all documents where the `address.city` is "QUEENS VLG".**

In [98]:
query7 = {"address.city": "QUEENS VLG"}

In [99]:
result7 = myCollection.find(query7)

In [101]:
Output_head(result7, 2)

{'_id': ObjectId('56d61033a378eccde8a83a25'),
 'address': {'city': 'QUEENS VLG',
             'number': 10126,
             'street': '217TH PL',
             'zip': 11429},
 'business_name': 'AHMED, CHAUDHRY I',
 'certificate_number': 9316871,
 'date': 'Jun 20 2015',
 'id': '36328-2015-ENFO',
 'result': 'No Violation Issued',
 'sector': 'Home Improvement Contractor - 100'}
------------------------------------------------------------

{'_id': ObjectId('56d61033a378eccde8a84006'),
 'address': {'city': 'QUEENS VLG',
             'number': 21025,
             'street': 'JAMAICA AVE',
             'zip': 11428},
 'business_name': 'MEJIA, NELSON RAMON',
 'certificate_number': 9273157,
 'date': 'Jun 16 2015',
 'id': '67625-2014-ENFO',
 'result': 'No Violation Issued',
 'sector': 'Electronic Store - 001'}
------------------------------------------------------------



-----------------

**Q8. Retrieve all documents where the `address.zip` is 11428.**

In [103]:
query8 = {"address.zip": 11428}

In [104]:
projection8 = {}

In [105]:
result8 = myCollection.find(query8, projection8)

In [107]:
Output_head(result8, 2)

{'_id': ObjectId('56d61033a378eccde8a83552'),
 'address': {'city': 'QUEENS VLG',
             'number': 9440,
             'street': '210TH ST',
             'zip': 11428},
 'business_name': 'A&C CHIMNEY CORP.',
 'certificate_number': 5346909,
 'date': 'Apr 22 2015',
 'id': '1012-2015-CMPL',
 'result': 'Violation Issued',
 'sector': 'Home Improvement Contractor - 100'}
------------------------------------------------------------

{'_id': ObjectId('56d61033a378eccde8a8394d'),
 'address': {'city': 'QUEENS VILLAGE',
             'number': 9130,
             'street': '221ST PL',
             'zip': 11428},
 'business_name': 'MD HOSSAIN',
 'certificate_number': 9285676,
 'date': 'Jun  8 2015',
 'id': '33685-2015-ENFO',
 'result': 'No Violation Issued',
 'sector': 'Mobile Food Vendor - 881'}
------------------------------------------------------------



-------

**Q9. Retrieve all documents where the `sector` is "Cigarette Retail Dealer - 127".**

In [109]:
query9 = {"sector": "Cigrarette Retail Dealer - 127"}

In [118]:
result9 = myCollection.find(query9)

In [113]:
Output_head(result9, 2)

In [119]:
len(list(result9))

0

> the result is empty

--------

**Q10 - Find the business with the `certificate_number` 5381180**

In [120]:
query10 = {"certificate_number": 5381180}

In [128]:
result10 = myCollection.find(query10)

In [129]:
Output_head(result10, 1)

{'_id': ObjectId('56d61033a378eccde8a83553'),
 'address': {'city': 'STATEN ISLAND',
             'number': 1233,
             'street': 'TODT HILL RD',
             'zip': 10304},
 'business_name': 'ERIC CONSTRUCTION AND DECORATING INC.',
 'certificate_number': 5381180,
 'date': 'Sep  8 2015',
 'id': '10127-2015-CMPL',
 'result': 'Violation Issued',
 'sector': 'Home Improvement Contractor - 100'}
------------------------------------------------------------



--------

__Q11. Retrieve the `id` and `date` for all businesses.__

In [131]:
query11 = {}

In [138]:
projection11 = {"id": 1, 
                "_id": 0,
                "date": 1}

In [139]:
result11 = myCollection.find(query11, projection11)

In [142]:
Output_head(result11, 4)

{'date': 'Feb 26 2015', 'id': '10391-2015-ENFO'}
------------------------------------------------------------

{'date': 'Dec 23 2015', 'id': '1044-2016-ENFO'}
------------------------------------------------------------

{'date': 'Jul 17 2015', 'id': '10423-2015-CMPL'}
------------------------------------------------------------

{'date': 'Jul 22 2015', 'id': '1044-2015-CMPL'}
------------------------------------------------------------



-----

__Q12. Find all documents where the `certificate_number` is exactly 9278806.__

In [143]:
query12 = {"certificate_number": 9278806}

In [149]:
result12 = myCollection.find(query12)

In [150]:
Output_head(result12, 2)

{'_id': ObjectId('56d61033a378eccde8a8354f'),
 'address': {'city': 'RIDGEWOOD',
             'number': 1712,
             'street': 'MENAHAN ST',
             'zip': 11385},
 'business_name': 'ATLIXCO DELI GROCERY INC.',
 'certificate_number': 9278806,
 'date': 'Feb 20 2015',
 'id': '10021-2015-ENFO',
 'result': 'No Violation Issued',
 'sector': 'Cigarette Retail Dealer - 127'}
------------------------------------------------------------



--------

__Q13. List all businesses whose `address.city` is "NEW YORK".__

In [151]:
query13 = {"address.city": "NEW YORK"}

In [152]:
result13 = myCollection.find(query13)

In [153]:
Output_head(result13, 2)

{'_id': ObjectId('56d61033a378eccde8a83558'),
 'address': {'city': 'NEW YORK',
             'number': 2645,
             'street': 'FREDRCK D BLVD',
             'zip': 10030},
 'business_name': 'GRICEYDA M VILLAR',
 'certificate_number': 9287090,
 'date': 'Feb 25 2015',
 'id': '10312-2015-ENFO',
 'result': 'No Violation Issued',
 'sector': 'Salons And Barbershop - 841'}
------------------------------------------------------------

{'_id': ObjectId('56d61033a378eccde8a83567'),
 'address': {'city': 'NEW YORK',
             'number': 2254,
             'street': '2ND AVE',
             'zip': 10029},
 'business_name': 'EAGLE TILE & HOME CENTER, INC.',
 'certificate_number': 9302188,
 'date': 'Mar  2 2015',
 'id': '10559-2015-ENFO',
 'result': 'No Violation Issued',
 'sector': 'Home Improvement Contractor - 100'}
------------------------------------------------------------



--------

__Q14. Find all documents where the `address.street` is "214TH ST".__

In [154]:
query14 = {"address.street": "214TH ST"}

In [192]:
result14 = myCollection.find(query14)

In [193]:
Output_head(result14, 2)

{'_id': ObjectId('56d61033a378eccde8a83551'),
 'address': {'city': 'QUEENS VLG',
             'number': 8823,
             'street': '214TH ST',
             'zip': 11427},
 'business_name': 'MICHAEL GOMEZ RANGHALL',
 'certificate_number': 9278914,
 'date': 'Feb 10 2015',
 'id': '10084-2015-ENFO',
 'result': 'No Violation Issued',
 'sector': 'Locksmith - 062'}
------------------------------------------------------------



-------------

__Q15. Retrieve the `business_name` and `sector` of all businesses inspected after "Feb 15 2015".__

In [15]:
query15 = {"date": {"$gt": datetime(2015, 2, 1)}}

In [16]:
projection15 = {"_id": 0,
               "business_name": 1,
               "sector": 1}

In [17]:
result15 = myCollection.find(query15, projection15)

In [18]:
Output_head(result15, 2)

{'business_name': 'UNNAMED HOT DOG VENDOR LICENSE NUMBER TA01158',
 'sector': 'Mobile Food Vendor - 881'}
------------------------------------------------------------

{'business_name': 'UNNAMED HOT DOG VENDOR NO LICENSE NUMBER PROVIDED',
 'sector': 'Mobile Food Vendor - 881'}
------------------------------------------------------------



---

__Q16. Find documents where the `business_name` starts with the letter "A".__

In [37]:
query16 = {"business_name": {"$regex": re.compile("^A")}}

In [38]:
result16 = myCollection.find(query16)

In [40]:
Output_head(result16, 2)

{'_id': ObjectId('56d61033a378eccde8a8355a'),
 'address': {'city': 'JERSEY CITY',
             'number': 70,
             'street': 'TONNELE AVE',
             'zip': 7306},
 'business_name': 'AYAD YOUSSEF',
 'certificate_number': 9305498,
 'date': datetime.datetime(2015, 7, 23, 0, 0),
 'id': '10290-2015-CMPL',
 'result': 'No Violation Issued',
 'sector': 'Mobile Food Vendor - 881'}
------------------------------------------------------------

{'_id': ObjectId('56d61033a378eccde8a8354f'),
 'address': {'city': 'RIDGEWOOD',
             'number': 1712,
             'street': 'MENAHAN ST',
             'zip': 11385},
 'business_name': 'ATLIXCO DELI GROCERY INC.',
 'certificate_number': 9278806,
 'date': datetime.datetime(2015, 2, 20, 0, 0),
 'id': '10021-2015-ENFO',
 'result': 'No Violation Issued',
 'sector': 'Cigarette Retail Dealer - 127'}
------------------------------------------------------------



-------

__Q17. List all documents where the `result` is either "Violation Issued" or "No Violation Issued".__

In [48]:
query17 = {"$or": [{"result": "Violation Issued"}, {"result": "No Violation Issued"}]}

In [49]:
result17 = myCollection.find(query17)

In [51]:
Output_head(result17, 2)

{'_id': ObjectId('56d61033a378eccde8a83556'),
 'address': {'city': '', 'number': '', 'street': '', 'zip': ''},
 'business_name': 'UNNAMED HOT DOG VENDOR NO LICENSE NUMBER PROVIDED',
 'certificate_number': 9304816,
 'date': datetime.datetime(2015, 8, 19, 0, 0),
 'id': '10268-2015-CMPL',
 'result': 'No Violation Issued',
 'sector': 'Mobile Food Vendor - 881'}
------------------------------------------------------------

{'_id': ObjectId('56d61033a378eccde8a8355b'),
 'address': {'city': 'ELMHURST',
             'number': 4157,
             'street': '75TH ST',
             'zip': 11373},
 'business_name': 'BISHWANATH BISWAS',
 'certificate_number': 9287092,
 'date': datetime.datetime(2015, 2, 25, 0, 0),
 'id': '10318-2015-ENFO',
 'result': 'No Violation Issued',
 'sector': 'Mobile Food Vendor - 881'}
------------------------------------------------------------



----------

__Q18. Count the total number of businesses in the collection.__

In [53]:
result18 = myCollection.count_documents({})

In [56]:
result18

81047

-----

__Q19. Retrieve businesses whose `address.zip` code is between 10000 and 12000__

In [60]:
query19 = {"$and": [{"address.zip": {"$lt": 12000}}, {"address.zip": {"$gt": 10000}}]}

In [61]:
result19 = myCollection.find(query19)

In [63]:
Output_head(result19, 2)

{'_id': ObjectId('56d61033a378eccde8a83558'),
 'address': {'city': 'NEW YORK',
             'number': 2645,
             'street': 'FREDRCK D BLVD',
             'zip': 10030},
 'business_name': 'GRICEYDA M VILLAR',
 'certificate_number': 9287090,
 'date': datetime.datetime(2015, 2, 25, 0, 0),
 'id': '10312-2015-ENFO',
 'result': 'No Violation Issued',
 'sector': 'Salons And Barbershop - 841'}
------------------------------------------------------------

{'_id': ObjectId('56d61033a378eccde8a83553'),
 'address': {'city': 'STATEN ISLAND',
             'number': 1233,
             'street': 'TODT HILL RD',
             'zip': 10304},
 'business_name': 'ERIC CONSTRUCTION AND DECORATING INC.',
 'certificate_number': 5381180,
 'date': datetime.datetime(2015, 9, 8, 0, 0),
 'id': '10127-2015-CMPL',
 'result': 'Violation Issued',
 'sector': 'Home Improvement Contractor - 100'}
------------------------------------------------------------



--------

__Q20. Find documents where the `address.number` is greater than 9000.__

In [64]:
query20 = {"address.number": {"$gt": 9000}}

In [65]:
result20 = myCollection.find(query20)

In [67]:
Output_head(result20, 2)

{'_id': ObjectId('56d61033a378eccde8a8355c'),
 'address': {'city': 'S RICHMOND HL',
             'number': 11420,
             'street': '101ST AVE',
             'zip': 11419},
 'business_name': 'H & H FURNITURE',
 'certificate_number': 5347333,
 'date': datetime.datetime(2015, 4, 29, 0, 0),
 'id': '1033-2015-CMPL',
 'result': 'Violation Issued',
 'sector': 'Home Improvement Contractor - 100'}
------------------------------------------------------------

{'_id': ObjectId('56d61033a378eccde8a83569'),
 'address': {'city': 'SOUTH OZONE PARK',
             'number': 12705,
             'street': '111TH AVE',
             'zip': 11420},
 'business_name': 'R&S HOME IMPROVEMENT & CABINETRY INC.',
 'certificate_number': 5381188,
 'date': datetime.datetime(2015, 11, 6, 0, 0),
 'id': '10682-2015-CMPL',
 'result': 'Violation Issued',
 'sector': 'Home Improvement Contractor - 100'}
------------------------------------------------------------



---------

__Q21. Retrieve all documents where the `address.number` is 1233.__

In [68]:
query21 = {"address.number": 1233}

In [69]:
result21 = myCollection.find(query21)

In [71]:
Output_head(result21, 2)

{'_id': ObjectId('56d61033a378eccde8a837d1'),
 'address': {'city': 'STATEN ISLAND',
             'number': 1233,
             'street': 'TODT HILL RD',
             'zip': 10304},
 'business_name': 'ERIK CONSTRUCTION & DECORATING INC',
 'certificate_number': 9284512,
 'date': datetime.datetime(2015, 7, 29, 0, 0),
 'id': '3031-2015-CMPL',
 'result': 'No Violation Issued',
 'sector': 'Home Improvement Contractor - 100'}
------------------------------------------------------------

{'_id': ObjectId('56d61033a378eccde8a89781'),
 'address': {'city': 'NEW YORK',
             'number': 1233,
             'street': 'LEXINGTON AVE',
             'zip': 10028},
 'business_name': "D'AGOSTINO SUPERMARKETS, INC.",
 'certificate_number': 3044068,
 'date': datetime.datetime(2015, 8, 12, 0, 0),
 'id': '47121-2015-ENFO',
 'result': 'Pass',
 'sector': 'Supermarket - 819'}
------------------------------------------------------------



------

__Q22. List the `business_name` of businesses whose `sector` contains the word "Contractor".__

In [72]:
query22 = {"sector": {"$regex": re.compile("Contractor")}}

In [73]:
projection22 = {"business_name": 1,
               "_id": 0}

In [74]:
result22 = myCollection.find(query22, projection22)

In [75]:
Output_head(result22, 2)

{'business_name': 'ERIC CONSTRUCTION AND DECORATING INC.'}
------------------------------------------------------------

{'business_name': 'NEW FINEST BUILDERS INC'}
------------------------------------------------------------



---------

__Q23. Find businesses where the `address.city` is either "RIDGEWOOD" or "NEW YORK".__

In [76]:
query23 = {"address.city": {"$in": ["RIDGEWOOD", "NEW YORK"]}}

In [77]:
result23 = myCollection.find(query23)

In [79]:
Output_head(result23, 2)

{'_id': ObjectId('56d61033a378eccde8a83567'),
 'address': {'city': 'NEW YORK',
             'number': 2254,
             'street': '2ND AVE',
             'zip': 10029},
 'business_name': 'EAGLE TILE & HOME CENTER, INC.',
 'certificate_number': 9302188,
 'date': datetime.datetime(2015, 3, 2, 0, 0),
 'id': '10559-2015-ENFO',
 'result': 'No Violation Issued',
 'sector': 'Home Improvement Contractor - 100'}
------------------------------------------------------------

{'_id': ObjectId('56d61033a378eccde8a83559'),
 'address': {'city': 'NEW YORK',
             'number': 2653,
             'street': 'FREDRCK D BLVD',
             'zip': 10030},
 'business_name': 'NYC CANDY STORE SHOP CORP',
 'certificate_number': 9287089,
 'date': datetime.datetime(2015, 2, 25, 0, 0),
 'id': '10302-2015-ENFO',
 'result': 'No Violation Issued',
 'sector': 'Cigarette Retail Dealer - 127'}
------------------------------------------------------------



----------

__Q24. Retrieve the `business_name`, `date`, and `result` for all businesses with a `certificate_number` less than 7000000.__

In [82]:
query24 = {"certificate_number": {"$lt": 7000000}}

In [83]:
result24 = myCollection.find(query24)

In [84]:
Output_head(result24, 2)

{'_id': ObjectId('56d61033a378eccde8a83553'),
 'address': {'city': 'STATEN ISLAND',
             'number': 1233,
             'street': 'TODT HILL RD',
             'zip': 10304},
 'business_name': 'ERIC CONSTRUCTION AND DECORATING INC.',
 'certificate_number': 5381180,
 'date': datetime.datetime(2015, 9, 8, 0, 0),
 'id': '10127-2015-CMPL',
 'result': 'Violation Issued',
 'sector': 'Home Improvement Contractor - 100'}
------------------------------------------------------------

{'_id': ObjectId('56d61033a378eccde8a8355d'),
 'address': {'city': 'BROOKLYN',
             'number': 1320,
             'street': 'E 55TH ST',
             'zip': 11234},
 'business_name': 'NEW FINEST BUILDERS INC',
 'certificate_number': 5381196,
 'date': datetime.datetime(2015, 12, 1, 0, 0),
 'id': '10351-2015-CMPL',
 'result': 'Violation Issued',
 'sector': 'Home Improvement Contractor - 100'}
------------------------------------------------------------



-----

__Q25. Find all documents sorted by `date` in ascending order.__

In [85]:
result25 = myCollection.find().sort({"date": 1})

In [86]:
Output_head(result25, 2)

{'_id': ObjectId('56d61033a378eccde8a85083'),
 'address': {'city': 'BROOKLYN',
             'number': 995,
             'street': 'FULTON ST',
             'zip': 11238},
 'business_name': 'VU QUANG DANG',
 'certificate_number': 9277585,
 'date': datetime.datetime(2015, 1, 2, 0, 0),
 'id': '231-2015-ENFO',
 'result': 'Out of Business',
 'sector': 'Salons And Barbershop - 841'}
------------------------------------------------------------

{'_id': ObjectId('56d61034a378eccde8a908d6'),
 'address': {'city': 'FAR ROCKAWAY',
             'number': 2210,
             'street': 'BROOKHAVEN AVE',
             'zip': 11691},
 'business_name': 'PROPARK AMERICA NEW YORK, LLC',
 'certificate_number': 5345334,
 'date': datetime.datetime(2015, 1, 2, 0, 0),
 'id': '475-2015-ENFO',
 'result': 'Violation Issued',
 'sector': 'Parking Lot - 050'}
------------------------------------------------------------



------------

__Q26. List the `id` values of businesses with the `result` "No Violation Issued"__

In [87]:
query26 = {"result": "No Violation Issued"}

In [88]:
projection26 = {"id": 1,
               "_id": 0}

In [90]:
result26 = myCollection.find(query26, projection26)

In [91]:
Output_head(result26, 2)

{'id': '10172-2015-CMPL'}
------------------------------------------------------------

{'id': '10268-2015-CMPL'}
------------------------------------------------------------



----------

__Q27. Retrieve all documents where the `address.street` is "MENAHAN ST".__

In [92]:
query27 = {"address.street": "MENAHAN ST"}

In [93]:
result27 = myCollection.find(query27)

In [95]:
Output_head(result27, 2)

{'_id': ObjectId('56d61033a378eccde8a8780a'),
 'address': {'city': 'RIDGEWOOD',
             'number': 1712,
             'street': 'MENAHAN ST',
             'zip': 11385},
 'business_name': 'ATLIXCO DELI GROCERY INC.',
 'certificate_number': 50061434,
 'date': datetime.datetime(2015, 8, 11, 0, 0),
 'id': '46377-2015-ENFO',
 'result': 'No Violation Issued',
 'sector': 'Cigarette Retail Dealer - 127'}
------------------------------------------------------------



----------

__Q28. Find businesses whose `business_name` contains the word "GROCERY".__

In [98]:
query28 = {"business_name": {"$regex": "GROCERY", "$options": "i"}}

In [99]:
result28 = myCollection.find(query28)

In [101]:
Output_head(result28, 2)

{'_id': ObjectId('56d61033a378eccde8a83589'),
 'address': {'city': 'NEW YORK',
             'number': 570,
             'street': 'W 189TH ST',
             'zip': 10040},
 'business_name': 'FOOD GOURMET DELI-GROCERY, INC.',
 'certificate_number': 5373991,
 'date': datetime.datetime(2015, 3, 4, 0, 0),
 'id': '11525-2015-ENFO',
 'result': 'Violation Issued',
 'sector': 'Cigarette Retail Dealer - 127'}
------------------------------------------------------------

{'_id': ObjectId('56d61033a378eccde8a835d6'),
 'address': {'city': 'BRONX',
             'number': 555,
             'street': 'E 169TH ST',
             'zip': 10456},
 'business_name': 'NIN GROCERY CORP',
 'certificate_number': 70025940,
 'date': datetime.datetime(2015, 3, 21, 0, 0),
 'id': '14186-2015-ENFO',
 'result': 'Violation Issued',
 'sector': 'Cigarette Retail Dealer - 127'}
------------------------------------------------------------



--------

__Q29. List all businesses where the `sector` is not "Tax Preparers - 891"__

In [102]:
query29 = {"sector": {"$ne": "Tax Prepares - 891"}}

In [103]:
result29 = myCollection.find(query29)

In [104]:
Output_head(result29, 2)

{'_id': ObjectId('56d61033a378eccde8a83554'),
 'address': {'city': '', 'number': '', 'street': '', 'zip': ''},
 'business_name': 'UNNAMED HOT DOG VENDOR LICENSE NUMBER TA01158',
 'certificate_number': 9304489,
 'date': datetime.datetime(2015, 8, 21, 0, 0),
 'id': '10172-2015-CMPL',
 'result': 'No Violation Issued',
 'sector': 'Mobile Food Vendor - 881'}
------------------------------------------------------------

{'_id': ObjectId('56d61033a378eccde8a83556'),
 'address': {'city': '', 'number': '', 'street': '', 'zip': ''},
 'business_name': 'UNNAMED HOT DOG VENDOR NO LICENSE NUMBER PROVIDED',
 'certificate_number': 9304816,
 'date': datetime.datetime(2015, 8, 19, 0, 0),
 'id': '10268-2015-CMPL',
 'result': 'No Violation Issued',
 'sector': 'Mobile Food Vendor - 881'}
------------------------------------------------------------



---------

__Q30. Retrieve documents sorted by `certificate_number` in descending order.__

In [106]:
result30 = myCollection.find().sort({"certificate_number": -1})

In [108]:
Output_head(result30, 2)

{'_id': ObjectId('56d61035a378eccde8a96ab5'),
 'address': {'city': 'NEW YORK',
             'number': 42,
             'street': 'BROADWAY',
             'zip': 10004},
 'business_name': 'Lucious Auction House',
 'certificate_number': 'T7009000',
 'date': datetime.datetime(2016, 1, 19, 0, 0),
 'id': '1172-2016-CMPL',
 'result': 'Violation Issued',
 'sector': 'Auction House - 128'}
------------------------------------------------------------

{'_id': ObjectId('56d61034a378eccde8a8b50f'),
 'address': {'city': 'NEW YORK',
             'number': 79,
             'street': 'CLINTON ST',
             'zip': 10002},
 'business_name': 'Bottega Clinton LLC',
 'certificate_number': 'PP040015',
 'date': datetime.datetime(2015, 8, 28, 0, 0),
 'id': '48932-2015-ENFO',
 'result': 'Violation Issued',
 'sector': 'Restaurant - 818'}
------------------------------------------------------------



--------

## Medium Questions

__Q31. Find the number of businesses for each unique `result` type.__

In [9]:
query31 = [
    {
        "$group": {
            "_id": "$result",
            "count": {"$sum": 1}
        }
    }
]

In [10]:
result31 = myCollection.aggregate(query31)

In [12]:
Output_head(result31, 3)

{'_id': 'Unable to Complete Inspection', 'count': 41}
------------------------------------------------------------

{'_id': 'Out of Business', 'count': 7142}
------------------------------------------------------------

{'_id': 'Posting Order Served', 'count': 330}
------------------------------------------------------------



-----------

__Q32. List all businesses along with their `business_name` and `address.city`, sorted by `certificate_number` in ascending order.__

In [13]:
query32 = {}

In [14]:
projection32 = {
    "business_name": 1,
    "address.city": 1,
    "_id": 0
}

In [15]:
result32 = myCollection.find(query32, projection32).sort({"certificate_number": 1})

In [17]:
Output_head(result32, 2)

{'address': {'city': 'BRONX'},
 'business_name': 'EMPIRE COLLISION AND AUTO BODY INC.'}
------------------------------------------------------------

{'address': {'city': 'BROOKLYN'},
 'business_name': 'GRAY LINE NEW YORK TOURS, INC.'}
------------------------------------------------------------



-----------

__Q33. Find all businesses inspected in "QUEENS VLG" that received a "Violation Issued" result.__

In [18]:
query33 = {
    "address.city": "QUEENS VLG",
    "result": "Violation Issued"
}

In [19]:
result33 = myCollection.find(query33)

In [21]:
Output_head(result33, 2)

{'_id': ObjectId('56d61034a378eccde8a8d3b9'),
 'address': {'city': 'QUEENS VLG',
             'number': 21511,
             'street': 'JAMAICA AVE',
             'zip': 11428},
 'business_name': 'BAGHDAD DELI CORP',
 'certificate_number': 70033577,
 'date': datetime.datetime(2015, 7, 7, 0, 0),
 'id': '38559-2015-ENFO',
 'result': 'Violation Issued',
 'sector': 'Cigarette Retail Dealer - 127'}
------------------------------------------------------------

{'_id': ObjectId('56d61035a378eccde8a94580'),
 'address': {'city': 'QUEENS VLG',
             'number': 20801,
             'street': 'JAMAICA AVE',
             'zip': 11428},
 'business_name': 'QUEENS VILLAGE SUPERETTE CORP.',
 'certificate_number': 70026079,
 'date': datetime.datetime(2015, 6, 22, 0, 0),
 'id': '35218-2015-ENFO',
 'result': 'Violation Issued',
 'sector': 'Cigarette Retail Dealer - 127'}
------------------------------------------------------------



----------

__Q34. Count how many businesses belong to the `sector` "Home Improvement Contractor - 100".__

In [22]:
query34 = {
    "sector": "Home Improvement Contractor - 100"
}

In [23]:
result34 = myCollection.count_documents(query34)

In [25]:
result34

459

-------

__Q35. Find the average `address.number` for businesses in "QUEENS VLG".__

In [29]:
query35 = [
    {
        "$match": {
            "address.city" : "QUEENS VLG"
        }
    },
    {
        "$group": {
            "_id": None,
            "avgNumber": {
                "$avg": "$address.number"
            }
        }
    }
]

In [33]:
result35 = myCollection.aggregate(query35)

In [34]:
Output_head(result35, 2)

{'_id': None, 'avgNumber': 18113.590163934427}
------------------------------------------------------------



-----------

__Q36. List distinct `address.city` values where `result` is "Violation Issued".__

In [35]:
query36 = {
    "result" : "Violation Issued"
}

In [39]:
result36 = myCollection.distinct("address.city", query36)

In [42]:
Output_head(result36, 3)

''
------------------------------------------------------------

'ALLENTOWN'
------------------------------------------------------------

'ARLINGTON'
------------------------------------------------------------



-------

__Q37. Find the earliest inspection date recorded in the collection.__

In [47]:
result37 = myCollection.find({}).sort({"date": 1}).limit(1)

In [48]:
Output_head(result37)

{'_id': ObjectId('56d61033a378eccde8a83e41'),
 'address': {'city': 'BRONX',
             'number': 831,
             'street': 'ROSEDALE AVE',
             'zip': 10473},
 'business_name': 'WESTERN BEEF RETAIL, INC.',
 'certificate_number': 3033508,
 'date': datetime.datetime(2015, 1, 2, 0, 0),
 'id': '69752-2014-ENFO',
 'result': 'Pass',
 'sector': 'Supermarket - 819'}
------------------------------------------------------------



-------------

__Q38. Retrieve the top 3 businesses with the highest `certificate_number`.__

In [50]:
result38 = myCollection.find({}).sort({"certificate_number": -1}).limit(3)

In [51]:
Output_head(result38)

{'_id': ObjectId('56d61035a378eccde8a967c6'),
 'address': {'city': 'NEW YORK',
             'number': 42,
             'street': 'BROADWAY',
             'zip': 10004},
 'business_name': 'Test UAT',
 'certificate_number': 'T7009005',
 'date': datetime.datetime(2016, 1, 11, 0, 0),
 'id': '4496-2016-ENFO',
 'result': 'Violation Issued',
 'sector': 'Cigarette Retail Dealer - 127'}
------------------------------------------------------------

{'_id': ObjectId('56d61035a378eccde8a96ab5'),
 'address': {'city': 'NEW YORK',
             'number': 42,
             'street': 'BROADWAY',
             'zip': 10004},
 'business_name': 'Lucious Auction House',
 'certificate_number': 'T7009000',
 'date': datetime.datetime(2016, 1, 19, 0, 0),
 'id': '1172-2016-CMPL',
 'result': 'Violation Issued',
 'sector': 'Auction House - 128'}
------------------------------------------------------------



-------

__Q39. Count how many businesses have `address.zip` codes greater than 11000.__

In [52]:
query39 = {
    "address.zip": {
        "$gt": 11000
    }
}

In [53]:
result39 = myCollection.count_documents(query39)

In [54]:
result39

47027

-------

__Q40. Group businesses by `sector` and count how many businesses belong to each sector.__

In [55]:
query40 = [
    {
        "$group": {
            "_id": "$sector",
            "business_count": {
                "$sum": 1
            }
        }
    }
]

In [56]:
result40 = myCollection.aggregate(query40)

In [61]:
Output_head(result40)

{'_id': 'Jewelry Store-Retail - 823', 'business_count': 303}
------------------------------------------------------------

{'_id': 'Amusement Device (Temporary) - 090', 'business_count': 33}
------------------------------------------------------------



------------

__Q41. Find businesses where the `address.street` contains the word "ST" and `result` is "No Violation Issued".__

In [75]:
query41 = {
  "address.street": { "$regex": re.compile("ST") },
  "result": "No Violation Issued"
}

In [76]:
result41 = myCollection.find(query41)

In [77]:
Output_head(result41)

{'_id': ObjectId('56d61033a378eccde8a8355b'),
 'address': {'city': 'ELMHURST',
             'number': 4157,
             'street': '75TH ST',
             'zip': 11373},
 'business_name': 'BISHWANATH BISWAS',
 'certificate_number': 9287092,
 'date': datetime.datetime(2015, 2, 25, 0, 0),
 'id': '10318-2015-ENFO',
 'result': 'No Violation Issued',
 'sector': 'Mobile Food Vendor - 881'}
------------------------------------------------------------

{'_id': ObjectId('56d61033a378eccde8a83560'),
 'address': {'city': 'JERSEY CITY',
             'number': 160,
             'street': 'VROOM ST',
             'zip': 7306},
 'business_name': 'AZMY KIROLES',
 'certificate_number': 9318079,
 'date': datetime.datetime(2015, 12, 23, 0, 0),
 'id': '1044-2016-ENFO',
 'result': 'No Violation Issued',
 'sector': 'Mobile Food Vendor - 881'}
------------------------------------------------------------



-------

__Q42.Update the `result` to "Pending" for all businesses where the `result` is currently "No Violation Issued"__

In [78]:
query42 = {
    "result": "No Violation Issued"
}

In [79]:
Update42 = {
    "$set": {"result": "Pending"}
}

----------

__Q43. Delete all businesses with a `certificate_number` less than 6000000.__

In [80]:
query43 = {
    "certificate_number": {
        "$lt": 6000000
    }
}

--------------

__Q44. Find businesses inspected in "Feb 2015" and list their `business_name` and `result`.__

In [91]:
query44 = {
    "$and": [
        {
            "date": {"$gt": datetime(2015, 1, 31)}
        },
        {
            "date": {"$lt": datetime(2015, 3, 1)}
        }
    ]
}

In [92]:
projection44 = {
    "_id": 0,
    "business_name": 1,
    "result": 1
}

In [93]:
result44 = myCollection.find(query44, projection44)

In [94]:
Output_head(result44)

{'business_name': 'BISHWANATH BISWAS', 'result': 'No Violation Issued'}
------------------------------------------------------------

{'business_name': 'GRICEYDA M VILLAR', 'result': 'No Violation Issued'}
------------------------------------------------------------



---------

__Q45. Find all businesses whose `address.number` is between 8000 and 9500.__

In [95]:
query45 = {
    "$and": [
        {
            "address.number": {"$gt": 8000}
        },
        {
            "address.number": {"$lt": 9500}    
        }
    ]
}

In [96]:
result45 = myCollection.find(query45)

In [97]:
Output_head(result45)

{'_id': ObjectId('56d61033a378eccde8a83551'),
 'address': {'city': 'QUEENS VLG',
             'number': 8823,
             'street': '214TH ST',
             'zip': 11427},
 'business_name': 'MICHAEL GOMEZ RANGHALL',
 'certificate_number': 9278914,
 'date': datetime.datetime(2015, 2, 10, 0, 0),
 'id': '10084-2015-ENFO',
 'result': 'No Violation Issued',
 'sector': 'Locksmith - 062'}
------------------------------------------------------------

{'_id': ObjectId('56d61033a378eccde8a83552'),
 'address': {'city': 'QUEENS VLG',
             'number': 9440,
             'street': '210TH ST',
             'zip': 11428},
 'business_name': 'A&C CHIMNEY CORP.',
 'certificate_number': 5346909,
 'date': datetime.datetime(2015, 4, 22, 0, 0),
 'id': '1012-2015-CMPL',
 'result': 'Violation Issued',
 'sector': 'Home Improvement Contractor - 100'}
------------------------------------------------------------



--------

__Q46. Retrieve the list of businesses, projecting only `business_name`, `result`, and `address.zip`, sorted by `address.zip`.__

In [98]:
query46 = {}

In [99]:
projection46 = {
    "_id": 0,
    "business_name": 1,
    "result": 1,
    "address.zip": 1
}

In [100]:
result46 = myCollection.find(query46, projection46).sort({"address.zip": 1})

In [101]:
Output_head(result46, 3)

{'address': {'zip': 1069},
 'business_name': 'J & F ACQUITITIONS LLC',
 'result': 'Pass'}
------------------------------------------------------------

{'address': {'zip': 2886},
 'business_name': 'CITIZENS ASSET FINANCE INC',
 'result': 'Pass'}
------------------------------------------------------------

{'address': {'zip': 2886},
 'business_name': 'RBS ASSET FINANCE INC.',
 'result': 'Pass'}
------------------------------------------------------------



----------

__Q47. Find documents where the `address.zip` is either 11385 or 11427.__

In [102]:
query47 = {
    "address.zip":{
        "$in": [
            11385,
            11427
        ]
    }
}

In [103]:
result47 = myCollection.find(query47)

In [104]:
Output_head(result47)

{'_id': ObjectId('56d61033a378eccde8a83551'),
 'address': {'city': 'QUEENS VLG',
             'number': 8823,
             'street': '214TH ST',
             'zip': 11427},
 'business_name': 'MICHAEL GOMEZ RANGHALL',
 'certificate_number': 9278914,
 'date': datetime.datetime(2015, 2, 10, 0, 0),
 'id': '10084-2015-ENFO',
 'result': 'No Violation Issued',
 'sector': 'Locksmith - 062'}
------------------------------------------------------------

{'_id': ObjectId('56d61033a378eccde8a8354f'),
 'address': {'city': 'RIDGEWOOD',
             'number': 1712,
             'street': 'MENAHAN ST',
             'zip': 11385},
 'business_name': 'ATLIXCO DELI GROCERY INC.',
 'certificate_number': 9278806,
 'date': datetime.datetime(2015, 2, 20, 0, 0),
 'id': '10021-2015-ENFO',
 'result': 'No Violation Issued',
 'sector': 'Cigarette Retail Dealer - 127'}
------------------------------------------------------------



----------------

__Q48. Count how many unique `certificate_number` values exist in the collection.__

In [107]:
result48 = myCollection.distinct("certificate_number")

In [112]:
len(result48)

80794

-------------

__Q49. List the businesses where the `business_name` contains "INC" (case insensitive).__

In [116]:
query49 = {
    "business_name": {"$regex": "INC", 
                      "$options": "i"}
}

In [117]:
result49 = myCollection.find(query49)

In [118]:
Output_head(result49)

{'_id': ObjectId('56d61033a378eccde8a83553'),
 'address': {'city': 'STATEN ISLAND',
             'number': 1233,
             'street': 'TODT HILL RD',
             'zip': 10304},
 'business_name': 'ERIC CONSTRUCTION AND DECORATING INC.',
 'certificate_number': 5381180,
 'date': datetime.datetime(2015, 9, 8, 0, 0),
 'id': '10127-2015-CMPL',
 'result': 'Violation Issued',
 'sector': 'Home Improvement Contractor - 100'}
------------------------------------------------------------

{'_id': ObjectId('56d61033a378eccde8a8355d'),
 'address': {'city': 'BROOKLYN',
             'number': 1320,
             'street': 'E 55TH ST',
             'zip': 11234},
 'business_name': 'NEW FINEST BUILDERS INC',
 'certificate_number': 5381196,
 'date': datetime.datetime(2015, 12, 1, 0, 0),
 'id': '10351-2015-CMPL',
 'result': 'Violation Issued',
 'sector': 'Home Improvement Contractor - 100'}
------------------------------------------------------------



----------

__Q50. Find businesses whose `sector` ends with "100".__

In [126]:
query50 = {
    "sector": {"$regex": re.compile("100$")}
}

In [127]:
result50 = myCollection.find(query50)

In [128]:
Output_head(result50)

{'_id': ObjectId('56d61033a378eccde8a83553'),
 'address': {'city': 'STATEN ISLAND',
             'number': 1233,
             'street': 'TODT HILL RD',
             'zip': 10304},
 'business_name': 'ERIC CONSTRUCTION AND DECORATING INC.',
 'certificate_number': 5381180,
 'date': datetime.datetime(2015, 9, 8, 0, 0),
 'id': '10127-2015-CMPL',
 'result': 'Violation Issued',
 'sector': 'Home Improvement Contractor - 100'}
------------------------------------------------------------

{'_id': ObjectId('56d61033a378eccde8a8355d'),
 'address': {'city': 'BROOKLYN',
             'number': 1320,
             'street': 'E 55TH ST',
             'zip': 11234},
 'business_name': 'NEW FINEST BUILDERS INC',
 'certificate_number': 5381196,
 'date': datetime.datetime(2015, 12, 1, 0, 0),
 'id': '10351-2015-CMPL',
 'result': 'Violation Issued',
 'sector': 'Home Improvement Contractor - 100'}
------------------------------------------------------------



-----------

## Hard Questions

__Q51. Group businesses by `address.city` and calculate the average `certificate_number` for each city.__

In [136]:
query51 = [
    {
        "$group": {
            "_id": "$address.city",
            "avg_cert_num": {"$avg": "$certificate_number"}
        }
    }
]

In [137]:
result51 = myCollection.aggregate(query51)

In [138]:
Output_head(result51)

{'_id': 'WANTAGH', 'avg_cert_num': 9296115.0}
------------------------------------------------------------

{'_id': 'HIGHLAND', 'avg_cert_num': 4210833.5}
------------------------------------------------------------



----------

__Q52. Find the top 2 `sectors` with the highest number of "Violation Issued" results.__

In [139]:
query52 = [
    {
        "$match": {"result": "Violation Issued"}
    },    
    {
        "$group": {
            "_id": "$sector",
            "num_of_viol": {"$sum": 1}
        }
    },
    {
        "$sort":{
            "num_of_viol": -1
        }
    },
    {
        "$limit": 2
    }
]

In [141]:
result52 = myCollection.aggregate(query52)

In [142]:
Output_head(result52)

{'_id': 'Cigarette Retail Dealer - 127', 'num_of_viol': 3532}
------------------------------------------------------------

{'_id': 'Grocery-Retail - 808', 'num_of_viol': 2627}
------------------------------------------------------------



___

__Q53. Retrieve the `business_name` of the business with the latest inspection `date`.__

In [143]:
query53 = {}

In [145]:
projection53 = {
    "business_name": 1,
    "_id": 0
}

In [146]:
result53 = myCollection.find(query53, projection53).sort({"date": 1}).limit(1)

In [147]:
Output_head(result53)

{'business_name': 'WESTERN BEEF RETAIL, INC.'}
------------------------------------------------------------



-------

__Q54. Group businesses by `sector` and `result`, then count how many businesses fall into each combination.__

In [148]:
query54 = [
    {
        "$group": {
            "_id": {"sector": "$sector", "result": "$result"},
            "count": {"$sum": 1}
        }
    }
]

In [149]:
result54 = myCollection.aggregate(query54)

In [152]:
Output_head(result54)

{'_id': {'result': 'Violation Issued',
         'sector': 'Amusement Device (Temporary) - 090'},
 'count': 1}
------------------------------------------------------------

{'_id': {'result': 'Violation Issued', 'sector': 'Retail Store - 820'},
 'count': 6}
------------------------------------------------------------



------------------

__Q55. Find the percentage of businesses that received a "Violation Issued" result out of the total businesses.__

In [153]:
total = myCollection.count_documents({})

In [154]:
violation = myCollection.count_documents({"result": "Violation Issued"})

In [159]:
result55 = violation / total * 100

In [169]:
f"{result55:.2f}%"

'17.06%'

-------

__Q56. List businesses that have the same `address.zip` but different `result` values.__

In [170]:
query56 = [
  { "$group": {
      "_id": "$address.zip",
      "resultTypes": { "$addToSet": "$result" }
  }},
  { "$match": { "resultTypes.1": { "$exists": True } } }
]

In [172]:
result56 = myCollection.aggregate(query56)

In [173]:
Output_head(result56)

{'_id': 11231,
 'resultTypes': ['Warning',
                 'Posting Order Served',
                 'Re-inspection',
                 'No Violation Issued',
                 'Violation Issued',
                 'No Evidence of Activity',
                 'Pass',
                 'Out of Business',
                 'Closed',
                 'Fail',
                 'NOH Withdrawn']}
------------------------------------------------------------

{'_id': 10452,
 'resultTypes': ['Warning',
                 'No Violation Issued',
                 'Re-inspection',
                 'Pass',
                 'Posting Order Served',
                 'No Evidence of Activity',
                 'Violation Issued',
                 'Out of Business',
                 'Unable to Locate',
                 'Closed',
                 'Fail',
                 'Licensed',
                 'ECB Warning Issued']}
------------------------------------------------------------



------------

__Q57. Retrieve businesses whose `address.number` is higher than the average `address.number` of all businesses.__

```javascript
var avgNumber = db.businesses.aggregate([
  { $group: { _id: null, avgNumber: { $avg: "$address.number" } } }
]).toArray()[0].avgNumber;

db.businesses.find({ "address.number": { $gt: avgNumber } })
```


-----------

__Q58. For each `address.city`, count how many businesses have a `certificate_number` above 7000000.__

In [177]:
query58 = [
    {
        "$match": {"certificate_number": {"$gt": 7000000}}
    },{
        "$group": {
            "_id": "address.city",
            "count": {"$sum": 1 }
        }
    }
]

In [178]:
result58 = myCollection.aggregate(query58)

In [179]:
Output_head(result58)

{'_id': 'address.city', 'count': 57277}
------------------------------------------------------------



------------

__Q59. Find businesses with duplicate `certificate_number` values (if any).__

In [180]:
query59 = [
  {"$group": {
      "_id": "$certificate_number",
      "count": { "$sum": 1 }
  }},
  { "$match": { "count": { "$gt": 1 } } }
]

In [181]:
result59 = myCollection.aggregate(query59)

In [182]:
Output_head(result59)

{'_id': 9306529, 'count': 2}
------------------------------------------------------------

{'_id': 3048403, 'count': 2}
------------------------------------------------------------



____

__Q60. Group businesses by the month of the `date` and count how many inspections happened in each month.__

```javascript
db.businesses.aggregate([
  { $group: {
      _id: { $substr: ["$date", 0, 3] },
      count: { $sum: 1 }
  }}
])
```

-----------